### ISSUE TITLE
Failed to build with TP-Link Archer T4U V3 (kernel version)

### ISSUE THREAD

**Issue by HuakunShen** [fastoe/RTL8812BU#10]
It doesn't let me compile because my kernel version is 5.9.0, and the driver's version is 5.6.
Any idea about how to solve this?
Spent 4 days, still couldn't get Archer T4U working.
Thank you!

**Comment by pmfernandes** [comment]
I'm getting the same error.

**Comment by fastoe** [comment]
Clone new branch:
git clone -b v5.6.1 https://github.com/fastoe/RTL8812BU.git
cd RTL8812BU
make
sudo make install
sudo reboot
