### ISSUE TITLE
Trouble compiling on fedora 34 (linux kernel 5.11)

### ISSUE THREAD

**Issue by yakman2020** [fastoe/RTL8812BU#13]
I'm getting several issues here. The most obvious is 

      |                                 ^~~~~~
/usr/src/rtl88x2bu-5.6.1/os_dep/osdep_service.c:2247:32: error: ‘KERNEL_DS’ undeclared (first use in this function); did you mean ‘KERNFS_NS’?
 2247 |                         set_fs(KERNEL_DS);
      |                                ^~~~~~~~~
      |                                KERNFS_NS
/usr/src/rtl88x2bu-5.6.1/os_dep/osdep_service.c: In function ‘storeToFile’:
/usr/src/rtl88x2bu-5.6.1/os_dep/osdep_service.c:2284:33: error: incompatible types when assigning to type ‘mm_segment_t’ from type ‘int’
 2284 |                         oldfs = get_fs();
      |                                 ^~~~~~
/usr/src/rtl88x2bu-5.6.1/core/efuse/rtw_efuse.c: In function ‘rtw_efuse_analyze’:

I,m happy to mod the code if I know what you want here. Clearly the kernel interface has chaned.

**Comment by sudoLife** [comment]
@yakman2020 same here, kernel 5.12.9-1, Manjaro. lots and lots of errors of this kind.
Have you figured out the right changes?
