### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by Soundtoxin** [fastoe/RTL8812BU#17]
What license is this code? Can you add a LICENSE file?

**Comment by fastoe** [comment]
Please provide error information and operating system information.

**Comment by Soundtoxin** [comment]
I'm talking about like GPLv2 or MIT, etc. The repo defaults to all rights reserved / proprietary without a license. I believe this should've been licensed from Realtek already and you just removed or somehow forgot a license file. I am not running your software, there is no error and my OS is irrelevant.
