### ISSUE TITLE
Error! Bad return status for module build on kernel: 5.9.0-kali2-amd64 (x86_64)

### ISSUE THREAD

**Issue by Cala3len** [fastoe/RTL8812BU#7]
I get the following error trying to compile on Kali : 

```
make -j8 KERNELRELEASE=5.9.0-kali2-amd64 KVER=5.9.0-kali2-amd64 src=/usr/src/rtl88x2bu-5.3.1....(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.9.0-kali2-amd64 (x86_64)
```

[make.log](https://github.com/fastoe/RTL8812BU/files/5612634/make.log)

Config :

- Linux kali 5.9.0-kali2-amd64 #1 SMP Debian 5.9.6-1kali1 (2020-11-11) x86_64 GNU/Linux

- GNU Make 4.3

- gcc version 10.2.0 (Debian 10.2.0-16)

**Comment by Cala3len** [comment]
The device is a PC

**Comment by wukuy** [comment]
可以尝试安装
```bash
sudo apt install bc -y
```

**Comment by fastoe** [comment]
clone new branch:
git clone -b v5.6.1 https://github.com/fastoe/RTL8812BU.git
cd RTL8812BU
make
sudo make install
sudo reboot
