### ISSUE TITLE
Can't run dkms build command!

### ISSUE THREAD

**Issue by yarinz34** [fastoe/RTL8812BU#8]
I receive this error when applying "sudo dkms build -m rtl88x2bu -v ${VER}" command:
```
Error! echo
Your kernel headers for kernel 5.5.0-kali2-amd64 cannot be found at /lib/modules/5.5.0-kali2-amd64/build or /lib/modules/5.5.0-kali2-amd64/source.
```
I'm running this on a Kali2020.2 VM as guest on a Win10 host machine.

**Comment by HuakunShen** [comment]
I have the same problem. running kali 2020.4, kernel version: 5.9.0. 
Adapter: TP Link Archer T4U
The version in this repo isn't compatible.

**Comment by chriskran12** [comment]
I have the same issue!! 

Error! echo
Your kernel headers for kernel 5.9.0-kali1-amd64 cannot be found at
/lib/modules/5.9.0-kali1-amd64/build or /lib/modules/5.9.0-kali1-amd64/source.
You can use the --kernelsourcedir option to tell DKMS where it's located.

**Comment by fastoe** [comment]
clone new branch:
git clone -b v5.6.1 https://github.com/fastoe/RTL8812BU.git
cd RTL8812BU
make
sudo make install
sudo reboot

**Comment by fastoe** [comment]
> I have the same issue!!
> 
> Error! echo
> Your kernel headers for kernel 5.9.0-kali1-amd64 cannot be found at
> /lib/modules/5.9.0-kali1-amd64/build or /lib/modules/5.9.0-kali1-amd64/source.
> You can use the --kernelsourcedir option to tell DKMS where it's located.

download and install:
https://http.kali.org/kali/pool/main/l/linux/linux-headers-5.9.0-kali1-common_5.9.1-1kali2_all.deb
https://http.kali.org/kali/pool/main/l/linux/linux-kbuild-5.9_5.9.6-1kali1_amd64.deb
https://http.kali.org/kali/pool/main/l/linux/linux-headers-5.9.0-kali1-amd64_5.9.1-1kali2_amd64.deb

re-make.
